import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen text-white font-[Poppins] bg-gray-900">
        <div className="w-full shadow-lg">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
