import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-white font-[Inter] bg-[#1b1b23]">
        <div className="bg-[#343442]">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
